version: '3.8'
services:
  bill_manage_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8182:8182
    volumes:
      - .:/app
    depends_on:
      - bill_manage_api_db
  bill_manage_api_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: bill_manage_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33071:3306
